relics:
  scv:
    name: "SCV"
    description: "Terran worker unit. Gathers minerals and gas."
    passive_effects:
      - type: "resource_per_time"
        resource: "minerals"
        amount: 5
        interval: 1
      - type: "resource_per_time"
        resource: "gas"
        amount: 1
        interval: 3 